const BAD_REQUEST = 400;
const UNAUTHORIZED = 401
const FORBIDDEN_ERROR = 403;
const NOT_FOUND = 404;
const DUPLICATE = 409
const DEFAULT = 500;

module.exports = { BAD_REQUEST, NOT_FOUND, DEFAULT, FORBIDDEN_ERROR, DUPLICATE, UNAUTHORIZED };
